version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: quotes
      POSTGRES_USER: dns
      POSTGRES_PASSWORD: dns-quotes
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data: